# Site settings
title: Büşra Önder
description: Büşra Önder Kişisel Blog
keywords: Büşra, Önder,Blog,Mühendis Hanım
author: Büşra Önder
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://busraonder.me/
