
title: Büşra Önder
email: bbsronder@gmail.com
description: > Büşra Önder ,Necmettin Erbakan,Bilgisayar Mühendisliği,

url: "" http://busraonder.me
github_username:  BusraOnder

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
