
title: Büşra Önder
email: bbsronder@gmail.com
description:  Hello World
baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "http://busraonder.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

